name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Python ${{ matrix.python_version }}
    runs-on: ubuntu-20.04  # Ubuntu 20.04 is required for Python 3.6
    env:
      TOX_POSARGS: -- --cov=. --cov-report=xml
    strategy:
      matrix:
        python_version: ['3.6', '3.7', '3.8', '3.9']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python_version }}
        cache: 'pip'
        cache-dependency-path: 'requirements-test.txt'

    - name: Upgrade packaging tools
      run: python -m pip install --upgrade pip setuptools wheel

    - name: Install dependencies
      run: python -m pip install --upgrade codecov tox

    # Python 3.6 doesn't have tox4, so we need to install tox-py to imitate -f
    - name: Install tox-py for Python 3.6
      if: ${{ matrix.python_version == '3.6' }}
      run: python -m pip install --upgrade tox-py

    - name: Run tox targets for Python > 3.6 (currently ${{ matrix.python_version }})
      if: ${{ matrix.python_version != '3.6' }}
      run: tox run -f py$(echo ${{ matrix.python_version }} | tr -d .) ${{ env.TOX_POSARGS }}

    - name: Run tox targets for Python 3.6 (currently ${{ matrix.python_version }})
      if: ${{ matrix.python_version == '3.6' }}
      run: tox --py current ${{ env.TOX_POSARGS }}

    - name: Upload Coverage to Codecov
      if: ${{ matrix.python_version == '3.9' }}
      uses: codecov/codecov-action@v3
